---
title: "Research Proposal: A Tweet for Help? Using Sentiment and Dynamic Network Analysis to Gauge Risk of Suicide with Twitter Data"
author: "Bradley Carruthers, Supervisor: Milan Vojnovic"
date: \today
bibliography: ref.bib
csl: harvard-stellenbosch-university.csl
fontsize: 12pt
linestretch: 1.25  
output: pdf_document
---



# Context

## Rationale for study

A 2014 report by the World Health Organisation states that more than 800 000 people die by suicide each year worldwide [@WHO2014] and it is estimated that depression costs the United States $210 billion alone [@Greenberg2015]. These costs of mental illness to society may be surprising to the non-expert, since as @Chen2009 point out, there are less obvious negative externalities associated with suicide such as pyschological and financial burdens left on affected family members.

Within the last decade, a vast and growing quantity of heterogenous data has been streaming from social media platforms and their users, providing an exciting opportunity for research and the application of increasingly innovative and original methods such as dynamic network analysis and natural language processing [@Gruebner2017]. In my thesis therefore, I plan to use dynamic network analysis to expand on the current groundwork that has been laid in social media sentiment analysis and its application to mental illness [@Bollen2011, @Coppersmith2014, @DeChoudhury2013, @Dodds2011, @Glass2011, @Ravi2015, @Thelwall2010].


## Research Question

The exploratory research question is as follows: How can dynamic network analysis improve the identification of mental illness in social media data?



# Methodology and Timeline


## Data

I will scrape large quantities of Twitter data using Twitter's API.


## Timeline

\underline{Michaelmas Term:}

* Step 1: Summarise literature on dynamic network analysis

* Step 2: Summarise literature on sentiment analysis with social media as an application

* Step 3: Set up repository for developing code and trial-run scraping and cleaning a small dataset

\underline{Lent Term:}

* Step 4: Document research question and model

* Step 5: Refine workflow and model 

* Step 6: Deploy pipeline to cloud computing service for analysis on large dataset

\underline{Summer Term:}

* Step 7: Document analysis, results and visualisations

* Step 8: Refine and finalise results

* Step 9: Conclude writing up of analysis and results



# Limitations of Study

The main limitation of the study relates to the quality of the data. Since this would not be an experimental or quasi-experimental setting, there is little ground for answering questions of a causal nature. There is also a risk that dynamic network analysis will add very little to the existing literature and methods for social media sentiment analysis.



# Organisation of Study

Chapter 1: Introduction

Chapter 2: Dynamic Network Analysis Literature Review

Chapter 3: Social Media Sentiment Analysis Literature Review

Chapter 4: Model and Pipeline

Chapter 5: Results

Chapter 6: Recommendations for further research and conclusion

# References